### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by 3cl1ps** [TBouder/major.farm#2]
hey, got this error on firefox after adding the yearn crvsteth startegy.
after, whatever i do :
disconnect wallet, change browser, add farm
i always got this error

pm for address.

**Comment by TBouder** [comment]
Hey !
I am going to fix this, thank you for this issue

**Comment by TBouder** [comment]
The issue has been fixed, and we now display CRV prices based on the CRV minter `virtual_price`!
